# Generated by Django 6.0.2 on 2026-02-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_label', models.CharField(max_length=64)),
                ('diet', models.CharField(choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], default='omnivore', max_length=16)),
                ('favorite_foods', models.JSONField(default=list)),
                ('ordered_dishes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('waiter', 'Waiter'), ('customer', 'Customer')], max_length=16)),
                ('content', models.TextField()),
                ('turn_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'ordering': ['turn_index'],
                'unique_together': {('conversation', 'turn_index')},
            },
        ),
    ]
